FROM pteich/ubuntu:latest
MAINTAINER Peter Teich <peter.teich@gmail.com>

RUN curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -  && \
	  apt-get -y install nodejs && \
    rm -rf /var/lib/apt/lists/*
            
